### ISSUE TITLE
Chrome - Reading from top and not reading the latest message inserted

### ISSUE THREAD

**Issue by ris-mit** [Orange-OpenSource/a11y-guidelines#23]
Hi,

When I am using JAWS or NVDA it's not reading the latest message inserted inside the chat-content where you have given aria-live="polite". Whenever you give any message via textbox it starts reading from the top unnecessarily. It is specific to Chrome only.

**Comment by PigeardSylvain** [comment]
Hi ris-mit, thanks for your message.
I opened [an issue](https://bugs.chromium.org/p/chromium/issues/detail?id=934703&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=) on chrome last year.

The fix is coming, you can have more details on this problem in this NVDA issue : 
https://github.com/nvaccess/nvda/issues/10866

**Comment by ris-mit** [comment]
Hi @PigeardSylvain, I checked one way by adding the role=" alert" in the upcoming messages but then in return, it didn't help me to enter any new text inside the text box to chat with the bot while using the chat-bot. 

Do you think role=" alert" if can be handled with the text box it may work properly.

**Comment by PigeardSylvain** [comment]
I think the best way is to use aria-live, it should work fine in a few months even in chrome.

**Comment by ris-mit** [comment]
Hi @PigeardSylvain , I was checking some examples and came across [this](https://terrillthompson.com/tests/aria/live-scores.html). Here also they are using aria-live and aria-atomic and it is working for them in chrome. Don't know how.

**Comment by GaetanBt** [comment]
Could we close this ?
